(()=>{"use strict";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const ico=n=>'<i data-lucide="'+esc(n)+'"></i>';
const prLabel={essential:"핵심",common:"자주 씀",advanced:"확장"};
const weight={essential:0,common:1,advanced:2};
function render(b){
 if(b.type==="text")return '<section class="section"><h2>'+esc(b.title)+'</h2>'+(b.intro?'<p class="section-intro">'+esc(b.intro)+'</p>':'')+'<p>'+esc(b.body||"")+'</p></section>';
 if(b.type==="cards")return '<section class="section"><h2>'+esc(b.title)+'</h2>'+(b.intro?'<p class="section-intro">'+esc(b.intro)+'</p>':'')+'<div class="card-grid">'+(b.items||[]).map(x=>'<article class="card"><h3>'+esc(x.title)+'</h3><p>'+esc(x.body)+'</p>'+(x.code?'<code>'+esc(x.code)+'</code>':'')+'</article>').join("")+'</div></section>';
 if(b.type==="links")return '<section class="section"><h2>'+esc(b.title)+'</h2>'+(b.intro?'<p class="section-intro">'+esc(b.intro)+'</p>':'')+'<div class="link-grid">'+(b.items||[]).map(x=>'<a class="link-card" href="'+esc(x.href)+'"><h3>'+esc(x.title)+'</h3><p>'+esc(x.body)+'</p></a>').join("")+'</div></section>';
 if(b.type==="table")return '<section class="section"><h2>'+esc(b.title)+'</h2>'+(b.intro?'<p class="section-intro">'+esc(b.intro)+'</p>':'')+'<div class="table-wrap"><table><thead><tr>'+b.headers.map(x=>'<th>'+esc(x)+'</th>').join("")+'</tr></thead><tbody>'+b.rows.map(r=>'<tr>'+r.map((x,i)=>'<td>'+(i===0?'<code>'+esc(x)+'</code>':esc(x))+'</td>').join("")+'</tr>').join("")+'</tbody></table></div></section>';
 if(b.type==="code")return '<section class="section"><h2>'+esc(b.title)+'</h2>'+(b.intro?'<p class="section-intro">'+esc(b.intro)+'</p>':'')+'<div class="code-box"><div class="code-head"><span>'+ico("square-terminal")+' '+esc(b.label||"Terminal")+'</span><button class="copy-btn" type="button">'+ico("copy")+' <span>복사</span></button></div><pre>'+esc(b.code)+'</pre></div></section>';
 if(b.type==="callout")return '<div class="callout '+esc(b.tone||"")+'">'+ico(b.tone==="danger"?"triangle-alert":b.tone==="warn"?"circle-alert":b.tone==="good"?"circle-check":"info")+'<div><strong>'+esc(b.title)+'</strong><p>'+esc(b.body)+'</p></div></div>';
 if(b.type==="flow")return '<section class="section"><h2>'+esc(b.title)+'</h2>'+(b.intro?'<p class="section-intro">'+esc(b.intro)+'</p>':'')+'<div class="flow">'+b.items.map((x,i)=>'<div class="flow-item"><strong>'+esc(x.title)+'</strong><span>'+esc(x.body)+'</span></div>'+(i<b.items.length-1?'<span class="flow-arrow">'+ico("arrow-right")+'</span>':'')).join("")+'</div></section>';
 if(b.type==="steps")return '<section class="section"><h2>'+esc(b.title)+'</h2>'+(b.intro?'<p class="section-intro">'+esc(b.intro)+'</p>':'')+'<div class="steps">'+b.items.map(x=>'<div class="step"><div><strong>'+esc(x.title)+'</strong><span>'+esc(x.body)+'</span></div></div>').join("")+'</div></section>';
 if(b.type==="commands")return '<section class="section command-section"><h2>'+esc(b.title)+'</h2><p class="section-intro">'+esc(b.intro||"")+'</p><div class="command-toolbar" id="commandFilters"><button class="chip active" data-p="essential">핵심</button><button class="chip" data-p="common">자주 씀</button><button class="chip" data-p="advanced">확장</button><button class="chip" data-p="all">전체</button></div><div class="command-grid" id="commandGrid">'+b.items.map(c=>'<article class="command-card" data-priority="'+esc(c.priority)+'" data-search="'+esc((c.command+" "+c.summary+" "+(c.tags||[]).join(" ")).toLowerCase())+'"><div class="command-name">'+esc(c.command)+'</div><div class="command-desc">'+esc(c.summary)+'<span class="command-example">'+esc(c.example||"")+'</span></div><span class="priority '+esc(c.priority)+'">'+esc(prLabel[c.priority]||c.priority)+'</span></article>').join("")+'</div></section>';
 return "";
}
async function init(){
 const body=document.body,root=document.documentElement,siteUrl=body.dataset.site,pageUrl=body.dataset.page,rootRel=body.dataset.root||"./";
 const [site,page]=await Promise.all([fetch(siteUrl).then(r=>r.json()),fetch(pageUrl).then(r=>r.json())]);
 root.dataset.os=site.slug;root.dataset.theme=localStorage.getItem("cli-theme")||"dark";
 const osRoot=new URL(rootRel,location.href),otherRoot=new URL(site.otherOsRoot,osRoot);
 const current=site.pages.find(x=>x.id===page.id)||site.pages[0],navPages=site.pages.filter(x=>x.nav!==false);
 const groups=[...new Set(navPages.map(x=>x.group))];
 const nav=groups.map(g=>'<div class="nav-group"><div class="nav-label">'+esc(g)+'</div>'+navPages.filter(x=>x.group===g).map(x=>'<a class="nav-link '+(x.id===page.id?"active":"")+'" href="'+new URL(x.path,osRoot).href+'">'+ico(x.icon||"file-text")+esc(x.title)+'</a>').join("")+'</div>').join("");
 const otherPage=new URL(current.path,otherRoot).href,searchAction=new URL("search/",osRoot).href,index=navPages.findIndex(x=>x.id===page.id),prev=index>0?navPages[index-1]:null,next=index>=0&&index<navPages.length-1?navPages[index+1]:null;
 body.innerHTML='<div class="nav-overlay" id="overlay"></div><div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-icon">'+ico(site.icon)+'</span><div><strong>'+esc(site.name)+'</strong><small>'+esc(site.subtitle)+'</small></div></div>'+nav+'</aside><div class="main"><header class="topbar"><div class="top-left"><button class="icon-btn" id="menuBtn" aria-label="메뉴 열기">'+ico("panel-left")+'</button><div class="page-context">'+esc(site.shortName)+' / <strong>'+esc(page.title)+'</strong></div></div><form class="search-form" action="'+searchAction+'"><span>'+ico("search")+'</span><input name="q" placeholder="명령어, 개념, 문제 검색" aria-label="검색"><button type="submit" aria-label="검색">'+ico("arrow-right")+'</button></form><div class="top-actions"><div class="os-switch"><a class="'+(site.slug==="macos"?"current":"")+'" href="'+(site.slug==="macos"?new URL("./",osRoot).href:otherPage)+'">macOS</a><a class="'+(site.slug==="ubuntu"?"current":"")+'" href="'+(site.slug==="ubuntu"?new URL("./",osRoot).href:otherPage)+'">Ubuntu</a></div><button class="icon-btn" id="themeBtn" aria-label="테마 변경">'+ico("sun-moon")+'</button></div></header><main class="content"><div class="breadcrumbs"><a href="'+new URL("../",osRoot).href+'">CLI</a>'+ico("chevron-right")+'<a href="'+new URL("./",osRoot).href+'">'+esc(site.shortName)+'</a>'+ico("chevron-right")+'<span>'+esc(page.title)+'</span></div><section class="hero"><p class="eyebrow">'+esc(page.eyebrow||current.group)+'</p><h1>'+esc(page.title)+'</h1><p class="lead">'+esc(page.description)+'</p>'+(page.goals?'<div class="goal-grid">'+page.goals.map((g,i)=>'<article class="goal"><span class="goal-num">'+(i+1)+'</span><div><h3>'+esc(g.title)+'</h3><p>'+esc(g.body)+'</p></div></article>').join("")+'</div>':'')+'</section><div id="pageBody">'+(page.blocks||[]).map(render).join("")+'</div><nav class="pager">'+(prev?'<a href="'+new URL(prev.path,osRoot).href+'"><small>이전</small><strong>'+esc(prev.title)+'</strong></a>':'<span></span>')+(next?'<a href="'+new URL(next.path,osRoot).href+'"><small>다음</small><strong>'+esc(next.title)+'</strong></a>':'')+'</nav></main></div></div>';
 const mobile=()=>matchMedia("(max-width:64rem)").matches,open=()=>body.classList.add("nav-open"),close=()=>body.classList.remove("nav-open");
 document.getElementById("menuBtn").onclick=()=>{if(mobile()) body.classList.contains("nav-open")?close():open(); else{body.classList.toggle("nav-collapsed");localStorage.setItem("cli-nav-collapsed",body.classList.contains("nav-collapsed")?"1":"0")}};
 if(!mobile()&&localStorage.getItem("cli-nav-collapsed")==="1")body.classList.add("nav-collapsed");
 document.getElementById("overlay").onclick=close;document.getElementById("themeBtn").onclick=()=>{const t=root.dataset.theme==="light"?"dark":"light";root.dataset.theme=t;localStorage.setItem("cli-theme",t)};
 document.querySelectorAll(".copy-btn").forEach(btn=>btn.onclick=async()=>{const v=btn.closest(".code-box").querySelector("pre").innerText,label=btn.querySelector("span");try{await navigator.clipboard.writeText(v);label.textContent="복사됨";setTimeout(()=>label.textContent="복사",900)}catch{}});
 if(page.kind==="commands"){const params=new URLSearchParams(location.search),q=(params.get("q")||"").toLowerCase();let p=params.get("priority")||"essential";const cards=[...document.querySelectorAll(".command-card")],chips=[...document.querySelectorAll(".chip")];const apply=()=>{cards.forEach(c=>c.hidden=!((p==="all"||c.dataset.priority===p)&&(!q||c.dataset.search.includes(q))));chips.forEach(x=>x.classList.toggle("active",x.dataset.p===p))};chips.forEach(x=>x.onclick=()=>{p=x.dataset.p;apply()});apply()}
 if(page.kind==="search"){const q=(new URLSearchParams(location.search).get("q")||"").trim().toLowerCase(),input=document.querySelector(".search-form input");input.value=q;const idx=await fetch(new URL(site.searchFile,osRoot)).then(r=>r.json()),terms=q.split(/\s+/).filter(Boolean);const scored=idx.filter(x=>terms.every(t=>(x.search||"").includes(t))).map(x=>({...x,score:(x.priority?weight[x.priority]??3:1)+(x.title.toLowerCase()===q?-5:0)+(x.title.toLowerCase().startsWith(q)?-2:0)})).sort((a,b)=>a.score-b.score||a.title.localeCompare(b.title));document.getElementById("pageBody").innerHTML='<section class="section"><h2>검색 결과</h2><p class="section-intro">'+(q?'\"'+esc(q)+'\" 결과 '+scored.length+'개':'검색어를 입력하세요.')+'</p><div class="result-list">'+(scored.length?scored.map(x=>'<a class="result" href="'+new URL(x.path,osRoot).href+(x.query?'?q='+encodeURIComponent(x.query):'')+'"><span class="result-type">'+esc(x.type)+'</span><div><strong>'+esc(x.title)+'</strong><p>'+esc(x.summary)+'</p></div>'+(x.priority?'<span class="priority '+esc(x.priority)+'">'+esc(prLabel[x.priority])+'</span>':'')+'</a>').join(""):'<div class="empty">검색 결과가 없습니다.</div>')+'</div></section>'}
 addEventListener("keydown",e=>{if(e.key==="/"&&document.activeElement?.tagName!=="INPUT"){e.preventDefault();document.querySelector(".search-form input")?.focus()}if(e.key==="Escape")close()});window.lucide?.createIcons();
}
addEventListener("DOMContentLoaded",()=>init().catch(e=>{console.error(e);document.body.innerHTML='<main class="portal-main"><h1>페이지 데이터를 불러오지 못했습니다.</h1></main>'}));
})();